name: Wasm and JS

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build C/C++ inside docker
      run: make wasm

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: |
        npm install

    - name: Run Jest tests
      run: |
        make test

    - name: Build js module from TS into lib/
      run: |
        make build

    - name: Show Builds
      run: |
        find c/out
        find lib